**Integrantes** (Grupo 7):



*   Jorge Palacios
*   Rodrigo Araos
* Fernando Guerrero
* Ademir Muñoz





#Instalación de librerías necesarias

In [ ]:
import numpy as np

#**Seccion 1**

#Estado

En el siguiente cuadro se muestra el estado inicial del problema. Cada estado se compone de una matriz de tamaño 16x16. Los elementos de esta matriz pueden variar entre los valores 0 y 1 (Una matriz binaria).

In [ ]:
# Set a random seed for reproducibility
np.random.seed(123)

# Generate a 16x16 matrix of random values between 0 and 1
initial_state = np.random.randint(2, size=(16, 16))


In [ ]:
# function that print a given matrix
def print_matrix(state):
  for row in state:
    print(row)

In [ ]:
print_matrix(initial_state)

[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


#Acción
Para este estado se define que una accion es intercambiar el valor de un elemento de tal forma que:

*   Si el elemento tiene un valor 1 se le asigna un valor 0
*   Si el elemento tiene un valor 0 se le asigna un valor 1

El siguiente codigo muestra como se realoza una acción en el elemento [0,0] del estado inicial.

In [ ]:
#initial_state[0, 0] = 1
print_matrix(initial_state)

[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
[0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
[1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
[0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
[0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
[1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
[1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
[1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
[0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
[1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
[1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
[0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
[0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
[0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
[0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
[0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]


En base a esto se pide completar la función *expand_node(state)*. Donde la funcion retorna una lista de todos los hijos que se pueden generar de un estado state dado. (10 pts)

In [ ]:
def expand_node(state):
    
    #Se crea una lista vacía donde almacenaremos todos los hijos del nodo recibido
    #por la función.
    listaHijo=[]

    #Dividimos el tamaño de la matriz en dos variables, largo y ancho respectivamente
    largo = len(state)
    ancho = len(state[0])

    #Con ayuda de un for anidado, recorremos la matriz por ambas dimensiones
    for i in range(largo):
      for j in range(ancho):

        #Creamos una copia de la matriz al principio de la iteración
        hijo=state.copy()

        #Si en la posición (i,j) encontramos un 1, lo cambiamos por un 0
        if hijo[i][j] == 1:
          hijo[i][j] = 0

        #Si en la posición (i,j) encontramos un 0, lo cambiamos por un 1
        elif hijo[i][j] == 0:
          hijo[i][j] = 1

        #Guardamos en nuestra lista la matriz copiada al inicio de la iteración,
        #tal que la siguiente copia corresponda a aquella que fue cambiada en la posición (i,j) 
        listaHijo.append(hijo)

    #Retornamos la lista de hijos que podemos obtener desde un estado dado
    return listaHijo





# Estado Meta

Para el ejercicio se considera como estado meta (o final) la matriz que se genera al usar la semilla 124 en numpy. La cual se muestra a continuación.



In [ ]:
# Set a random seed for reproducibility
np.random.seed(124)

# Generate a 16x16 matrix of random values between 0 and 1
final_state = np.random.randint(2, size=(16, 16))

print_matrix(final_state)

[0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1]
[1 0 0 0 0 0 1 1 1 0 0 0 1 1 1 1]
[1 1 1 0 0 0 1 1 1 0 0 1 1 1 1 1]
[0 1 0 0 0 1 0 1 1 0 0 1 1 0 1 0]
[0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 1]
[1 0 0 1 0 0 1 0 0 1 1 0 0 0 1 0]
[0 1 1 0 1 0 0 1 0 1 1 1 0 1 1 1]
[0 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0]
[0 1 0 1 1 0 1 0 0 1 0 0 0 1 1 1]
[1 0 0 0 1 1 0 0 0 0 1 0 1 1 1 0]
[1 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1]
[1 1 1 1 1 1 0 1 1 1 1 0 1 0 1 1]
[1 1 1 1 1 0 0 0 0 1 0 0 1 0 0 1]
[0 0 1 1 1 1 1 0 1 1 1 1 1 1 1 1]
[0 1 1 1 0 0 1 1 1 1 0 0 0 0 1 1]
[0 1 0 1 0 1 1 1 0 0 0 1 1 1 0 0]


Teniendo este estado meta, se requiere que implemente la función *is_goal(state)*. la cual devuelve un valor booleano true si el estado state es el estado meta. En caso de que no sea el estado meta la funcion debera devolvera un valor booleano false. (5 pts)

In [ ]:
def is_goal(state):
  #En dos variables, almacenamos el tamaño de la matriz
  largo = len(state)
  ancho = len(state[0])
  
  #Con dos ciclos for anidados, recorremos la matriz
  for i in range(largo):
    for j in range(ancho):
      #Verificamos si la posición en la que estamos actualmente en el estado es igual a la posición en nuestro estado meta
      if state[i][j] != final_state[i][j]:
        return False #Si no es así, retornamos False inmediatamente

  return True #Ya luego, como recorrimos la matriz por completo, podemos decir que este estado es nuestro objetivo,
              #por lo que retornamos True.

#**Seccion 2**

En esta esta seccion se debera implementar un algoritmo de busqueda. Para esto tendran que que implementar la función *evaluate(state)* la cual evalua el estado y retorna un el coste de este. Como recomendacion considere que cada elemento del estado el cual no sea igual al del estado meta incrementa en 1 el coste de este. (5 pts)



In [ ]:
def evaluate(state):
  #En dos variables, almacenamos el tamaño de la matriz
  largo = len(state)
  ancho = len(state[0])
  #Creamos un contador que almacena el costo, inicializado en cero
  cost = 0
  #Usamos un forloop anidado para recorrer los elementos de la matriz 
  for i in range(largo):
    for j in range(ancho):
      #Si el elemento en una posicion es distinto al de final_state, sumamos 1 al costo
      if state[i][j] != final_state[i][j]:
        cost = cost+1
  #finalmente retornamos el costo        
  return cost

Teniendo la función de evaluación ya desarrollada es posible implementar el algoritmo de busqueda informado. Para ello deberan escoger **una** (meta)heuristica* Y describir el algoritmo escogido cómo hemos descrito los algoritmos que hemos visto en clases. (15 pts)

*Algunas opciones de (meta)heuristicas pueden ser local search, genetic algorithm, tabu search, simulates annealing entre otros.


---

##Descripción del algoritmo
El siguiente algoritmo utiliza como base la metaheurística de **búsqueda greedy**, que al fin y al cabo resulta siendo una búsqueda local, solo que trabaja en una vecindad mucho más grande. En palabras simples, lo que este hace es comenzar con una solución inicial donde, luego de expandir su frontera, busca en dicha vecindad por una mejor solución. Si se encuentra, se reemplaza la solución actual por la nueva que el algoritmo ha encontrado, y así continua el proceso hasta que no se pueda seguir mejorando esta solución, es decir, si llegamos al estado objetivo.

Ahora bien, de forma general funciona de la siguiente manera:
1. Se crea un estado inicial, desde el cual se comenzará a buscar el estado meta y, por consecuencia, la mejor solución para llegar a nuestro estado meta, es decir, el mejor path (camino).
2. A partir de nuestro estado actual, se expande su frontera.
3. Dentro de esta frontera, buscamos aquella acción de menor costo. Esto lo podemos realizar mediante una función evaluadora, la que nos retorna el costo de un nuevo path.
4. Si encontramos una nueva mejor acción, ésta se agrega al path.

---

Despues deberan implementar el algoritmo en la función *heuristic(initial_state)*. Esta función recibe como parámetro el estado inicial y debe retornar como salida el conjunto de acciones que permita ir desde el estado inicial hasta el estado final. (10 pts)

In [ ]:
def heuristic(initial_state):
    #Se hace una copia del estado inicial para modificar
    state = initial_state.copy()

    #Se crea el PATH
    path = []

    #Se agrega al path el estado inicial
    path.append(initial_state)
    
    while (True):
        #Vemos si el estado actual es igual al estado final
        if (is_goal(state)):
          break

        #Expandimos la frontera a partir del estado actual, dándonos una lista de estados para recorrer
        lista = expand_node(state)
        
        #A continuación, buscamos la acción de menor costo
        menor = np.inf #Inicializamos la variable menor con un número muy grande, puesto que corresponderá al menor costo encontrado. 
                       #En este caso el valor inf proveído por la librería NumPy.
        posicion = -1 #Variable que corresponde a la posición en la que se encuentra el estado de menor costo hasta ese momento,
                      #desde el cual expandiremos su frontera en la siguiente iteración.

        for i in range (len(lista)): #Recorremos la lista de nodos en la frontera
            actual = evaluate(lista[i]) #Evaluamos el costo del estado actual
            
            #Si el estado actual posee un costo menor al anterior...
            if (actual < menor):
                menor = actual #Almacenaremos el costo de la posición en la variable "menor"
                posicion = i #El estado actual se convertirá en un posible candidato para expandir, hasta que finalice el ciclo for
        
        #Se agrega el nodo de menor costo en el path
        path.append(lista[posicion])
        #Se actualiza el estado
        state = lista[posicion].copy()
         
    #Se retorna el path encontrado     
    return path

Ya implementado el algoritmo se pide mostrar en pantalla los estados recorridos desde el estado inicial hasta el estado final (se recomienda utilizar el camino mas corto que hayan encontrado). (5 pts)

In [ ]:
caminos = heuristic(initial_state) #Ejecutamos la función que nos retorna el path
#Recorremos la lista
for i in range(len(caminos)):
    if (i == 0):
        print("\nInitial State :\n", str(caminos[i]))
    elif (i == len(caminos)-1):
        print("\nFinal State :\n", str(caminos[i]))
    else:
        print("\nAcción ",i," :\n", str(caminos[i]))    


Initial State :
 [[0 1 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
 [0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
 [1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 1 0 0 1 0 0 1 0]
 [0 1 0 0 0 0 1 0 1 1 0 0 0 1 0 0]
 [0 1 0 0 0 1 0 1 1 1 1 0 1 1 1 1]
 [0 0 1 1 1 1 1 0 0 1 1 1 0 1 0 0]
 [0 1 1 1 0 1 0 0 1 1 1 0 1 1 0 0]]

Acción  1  :
 [[0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 1]
 [0 1 1 0 0 0 1 1 1 0 1 0 0 0 0 1]
 [1 1 0 0 1 0 0 1 0 1 0 1 1 1 0 0]
 [0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 1]
 [0 0 0 0 1 0 0 1 1 1 1 0 0 0 0 1]
 [1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1]
 [1 0 0 0 1 0 0 1 1 1 0 1 1 0 0 1]
 [1 0 1 1 1 1 1 1 1 0 1 1 1 1 0 0]
 [0 1 1 0 0 1 1 0 0 0 1 0 1 1 0 0]
 [1 0 1 1 1 1 0 1 0 1 0 0 1 1 0 1]
 [1 1 0 1 1 1 1 0 0 1 1 0 0 1 0 0]
 [0 1 0 1 1 0 0 0 1 0